---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "01/27/2022"

quarter <- "Winter2022"

week_folder <- "01-27_Ur"


title <- "Subject Data Access Rights: Measurement of Ad Targeting Practices and Lessons For Future Transparency Mechanisms"


speaker <- "Blase Ur"
department <- "Computer Science"
university <- "University of Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2022/issues/3"
zoom_url <- "https://uchicago.zoom.us/j/96755762030?pwd=OHFQb280WU1lWWZib0RGUVZMdG43UT09"


#Papers

week_paper_ref0 <- "Wei, M., Stamos, M., Veys, S., Reitinger, N., Goodman, J., Herman, M., ... & Ur, B. (2020). What Twitter Knows: Characterizing Ad Targeting Practices, User Perceptions, and Ad Explanations Through Users' Own Twitter Data. In 29th {USENIX} Security Symposium ({USENIX} Security 20) (pp. 145-162)."
week_paper_file0 <- "ur_reading.pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Although targeted advertising has drawn significant attention from privacy researchers, many critical empirical questions remain. To develop a deeper understanding of the current targeting advertising ecosystem, we had 231 participants download their own Twitter data, containing ads they were shown and the associated targeting criteria, for measurement and to bootstrap a user study. We found many targeting mechanisms ignored by prior work — including advertiser-uploaded lists of specific users, lookalike audiences, and retargeting campaigns — are widely used on Twitter. Crucially, participants found these understudied practices among the most privacy invasive. I will discuss this project's lessons for data access rights and also discuss ongoing work focused on making companies' responses to data access requests under CCPA and GDPR more usable and useful.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>

<br><br>

<p class=footertext2>

**Blase Ur** is Neubauer Family Assistant Professor of Computer Science at the University of Chicago, where he researches security, privacy, human-computer interaction, and ethical AI. He directs the UChicago SUPERgroup, which uses data-driven methods to help users make better security and privacy decisions, as well as to improve the usability of complex computer systems. He has received an NSF CAREER Award (2021), a Quantrell Award for Undergraduate Teaching (2021), three best paper awards, and five honorable mention paper awards. He received the 2020 Allen Newell Award for Research Excellence, the 2018 SIGCHI Outstanding Dissertation Award, and the 2018 IEEE Cybersecurity Award for Practice. He holds degrees from Carnegie Mellon University (PhD and MS) and Harvard University (AB).
</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held virtually on Zoom and in-person in room 295 of 1155 East 60th St. If joining virtually, please join via Zoom ([link](`r zoom_url`)).

</p>

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a group comment (one post/group) on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository. </a> We will use a rotation system for group posting. All group 2 sub-groups are expected to post a question and attend this week, but group 1 sub-groups do not need to post and attendance is optional.

This week's readings:

- `r readings0`

<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:00 a.m. to 12:20 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
