---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "02/24/2022"

quarter <- "Winter2022"

week_folder <- "02-24_Leong"


title <- "Polarized brains on polarizing media: Divergent neural and semantic representations of political content"


speaker <- "Yuan Chang Leong"
department <- "Department of Psychology"
university <- "University of Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2022/issues/7"
zoom_url <- "https://uchicago.zoom.us/j/96755762030?pwd=OHFQb280WU1lWWZib0RGUVZMdG43UT09"


#Papers

week_paper_ref0 <- "Leong, Y. C., Chen, J., Willer, R., & Zaki, J. (2020). Conservative and liberal attitudes drive polarized neural responses to political content. Proceedings of the National Academy of Sciences, 117(44), 27731-27739."
week_paper_file0 <- "leong_reading.pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Political polarization manifests in different forms across many facets of American life - liberals and conservatives are polarized in terms of the news they watch, where they choose to live, and more recently, their willingness to wear a mask and be vaccinated. In my talk, I will examine polarization that occurs (1) at the level of individual brains (“neural polarization”) and (2) in how we use language (“semantic polarization”). I will first show how functional magnetic resonance imaging (fMRI) can be used to assess moment-to-moment similarities and differences in partisans’ neural responses as they consume real-world political content (e.g., news footage, political debates, campaign ads). Using this approach, we identify a neural correlate for the divergent processing of political information, and show that it tracks subsequent attitude polarization. I will then present preliminary results from new work examining how semantic associations of the same words differ between conservatives and liberals. Using word embedding models trained separately on conservative and liberal media sources, we characterize how words differ along different psychological dimensions between the two types of sources. Together, this line of work seeks to advance our understanding of how the electorate consumes political information, and how divergent responses to the same information contributes to polarizing our democracy.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>

<br><br>

<p class=footertext2>

**Yuan Chang (YC) Leong** is an Assistant Professor in the Department of Psychology. His research aims to understand the neural and computational mechanisms underlying motivational influences on human cognition. How do goals, desires and needs shape how people perceive and respond to the physical and social world? Are people inherently biased to see what they want to see? Why does the same news footage elicit strong yet opposing responses from people with different political beliefs? Research in his lab examines questions like these using functional magnetic resonance imaging (fMRI), computational modeling, psychophysics, physiological measures, eye-tracking, and naturalistic task paradigms.

</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held both in-person and virtually on Zoom. Students can come in-person to room 295 of 1155 East 60th St or watch virtually by joining via Zoom at the link provided: ([link](`r zoom_url`)).

</p>

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a group comment (one post/group) on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository. </a> We will use a rotation system for group posting. All group 2 sub-groups are expected to post a question and attend this week, but group 1 sub-groups do not need to post and attendance is optional.

This week's reading:

- `r readings0`

<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:00 a.m. to 12:20 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
