---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "01/20/2022"

quarter <- "Winter2022"

week_folder <- "01-20_Emery"


title <- "Reporting from the Front Lines of Social Media Research: from Quick and Dirty to Ideal"


speaker <- "Sherry Emery"
department <- "NORC"
university <- "University of Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2022/issues/2"
zoom_url <- "https://uchicago.zoom.us/j/96755762030?pwd=OHFQb280WU1lWWZib0RGUVZMdG43UT09"


#Papers

week_paper_ref0 <- "Kim, Y., Emery, S. L., Vera, L., David, B., & Huang, J. (2021). At the speed of Juul: measuring the Twitter conversation related to ENDS and Juul across space and time (2017–2018). Tobacco Control, 30(2), 137-146."
week_paper_file0 <- "SpeedOfJuul.pdf"

week_paper_ref1 <- "Huang, J., Duan, Z., Kwok, J., Binns, S., Vera, L. E., Kim, Y., ... & Emery, S. L. (2019). Vaping versus JUULing: how the extraordinary growth and marketing of JUUL transformed the US retail e-cigarette market. Tobacco Control, 28(2), 146-151."
week_paper_file1 <- "VapingVsJuuling.pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](",week_paper_file0,")")
  
readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** In brief, I plan to provide an overview of how my team has approached social media research in the service of informing public health policy.  We have worked on a range of projects, which demanded a variety of approaches that ranged from rudimentary and fast to very complex and expensive.  This talk will briefly describe data sources, analytic approaches and findings of exemplar studies, and open discussion about current challenges we are working on.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>

<br><br>

<p class=footertext2>

**Dr. Sherry Emery** is a Senior Fellow in Public Health and the Director of the Social Data Collaboratory at NORC at the University of Chicago.  Prior to joining NORC in 2016, Dr. Emery led a group of health communication researchers at the Institute for Health Research and Policy at UIC (where she was colleagues with Dr. Chriqui for over 10 years).  Her Ph.D. is in City and Regional Planning, from the University of North Carolina at Chapel Hill, and she earned an MBA from Columbia University.
</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held virtually on Zoom. Please join the meeting via Zoom ([link](`r zoom_url`)).
</p>

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a group comment (one post/group) on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository. </a> We will use a rotation system for group posting. All group 1 sub-groups are expected to post a question this week, but group 2 sub-groups do not need to post.

This week's readings:

- `r readings0`


<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:00 a.m. to 12:20 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
