---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "02/17/2022"

quarter <- "Winter2022"

week_folder <- "02-17_Axtell"


title <- "The Dynamics of U.S. Business Firms: Data, Theories, and Models"


speaker <- "Robert Axtell"
department <- "Computational Science"
university <- "George Mason University"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2022/issues/6"
zoom_url <- "https://uchicago.zoom.us/j/96755762030?pwd=OHFQb280WU1lWWZib0RGUVZMdG43UT09"


#Papers

week_paper_ref0 <- "Axtell, R. (2018). Endogenous firm dynamics and labor flows via heterogeneous agents. In Handbook of computational economics (Vol. 4, pp. 157-213). Elsevier."
week_paper_file0 <- "Handbook_chapter3_Axtell.pdf"

week_paper_ref1 <- "Axtell, R. (2016). 120 million agents self-organize into 6 million firms: A model of the US private sector. In Proceedings of the 2016 International Conference on Autonomous Agents & Multiagent Systems (pp. 806-816)."
week_paper_file1 <- "Axtell-AAMAS_p806.pdf"

#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")

```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Using micro-data on all U.S. firms having employees, I will first present several dozen gross empirical regularities, many new, having to do with firm sizes, ages, productivities, growth rates, financials, networks, and locations. I will then argue that conventional theories of the firm have little explanatory power vis-a-vis the patterns in the data. I will go on to propose a model that is capable of reproducing many of these patterns. It involves some 120 million agents, the size of the U.S. private sector workforce, who form 6 million firms, and is realized computationally using large-scale agent-based modeling (ABM). This model is an example of a full-scale ABM grounded in micro-data.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>

<br><br>

<p class=footertext2>

**Robert Axtell** is Professor of Computational Science at George Mason University, External Faculty Fellow at the Santa Fe Institute, Visiting Scientist at Google Research, and currently Visiting Professor at the Sloan School at MIT. He is a pioneer of agent-based modeling for computational social science research and co-author (with J.M. Epstein) of Growing Artificial Societies: Social Science from the Bottom Up (MIT Press). His research has been published in Science, Nature, Proceedings of the National Academy of Sciences, as well as in leading field journals like the American Economic Review, Computational and Mathematical Organization Theory, and Sustainability Science.

</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held virtually on Zoom. Students are still welcome to come in-person to room 295 of 1155 East 60th St to listen to the virtual talk. Please join via Zoom ([link](`r zoom_url`)).

</p>

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a group comment (one post/group) on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository. </a> We will use a rotation system for group posting. All group 1 sub-groups are expected to post a question and attend this week, but group 2 sub-groups do not need to post and attendance is optional.

This week's recommended readings:

- `r readings0`
- `r readings1`

<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:00 a.m. to 12:20 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
