---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "03/03/2022"

quarter <- "Winter2022"

week_folder <- "03-03_Epstein"


title <- "Agent_Zero and Generative Social Science"


speaker <- "Joshua Epstein"
department <- "NYU School of Global Public Health"
university <- "New York University"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2022/issues/9"
zoom_url <- "https://uchicago.zoom.us/j/96755762030?pwd=OHFQb280WU1lWWZib0RGUVZMdG43UT09"


#Papers

week_paper_ref0 <- "Epstein, J. M. (2014). Agent_Zero. Princeton University Press."
week_paper_file0 <- "Preface.pdf"

week_paper_ref1 <- "Epstein, J. M. (2014). Agent_Zero. Princeton University Press."
week_paper_file1 <- "Part_1_2.pdf"

week_paper_ref2 <- "Epstein, J. M. (2014). Agent_Zero. Princeton University Press."
week_paper_file2 <- "Part2.pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")
readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")
readings2 <- paste0("[", week_paper_ref2,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file2,")")

```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** This talk will explore the concept of Agent_Zero for modeling complex social, cultural and health-related phenomena. Agent_Zero s a mathematical and computational individual that can generate important, but insufficiently understood, social dynamics from the bottom up. First published by Epstein (2013), this new theoretical entity possesses emotional, deliberative, and social modules, each grounded in contemporary neuroscience. Agent_Zero’s observable behavior results from the interaction of these internal modules. When multiple Agent_Zeros interact with one another, a wide range of important, even disturbing, collective dynamics emerge. These dynamics are not straightforwardly generated using the canonical rational actor which has dominated mathematical social science since the 1940s. Following a concise exposition of the Agent_Zero model, this chapter offers a range of fertile research directions, including the use of realistic geographies and population levels, the exploration of new internal modules and new interactions among them, the development of formal axioms for modular agents, empirical testing, the replication of historical episodes, and practical applications. These may all serve to advance the Agent_Zero research program.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>

<br><br>

<p class=footertext2>

**Joshua Epstein** is Professor of Epidemiology in the NYU School of Global Public Health, and founding Director of the NYU Agent-Based Modeling Laboratory, with affiliated appointments at The Courant Institute of Mathematical Sciences, and the Department of Politics. Before joining NYU, he was Professor and Director of the Center for Advanced Modeling in the Social, Behavior, and Health Sciences at Johns Hopkins  with Joint appointments in Economics, Applied Mathematics, International Health, and Biostatistics. Before that, he was  Senior Fellow in Economic Studies at the Brookings Institution and Director of the Center on Social and Economic Dynamics. His research interest has been modeling complex social dynamics using mathematical and computational methods, notably the method of Agent-Based Modeling in which he is a recognized pioneer. For this transformative innovation, he was awarded the NIH Director’s Pioneer Award in 2008 and an Honorary Doctorate of Science from Amherst College in 2010. He was elected to the Society of Sigma XI in 2018, and in 2020 received the Rosaria Conte Award for Outstanding Contribution to Social Simulation from the European Social Simulation Association. He has applied this method to the study of infectious diseases (e.g., Ebola, pandemic influenza, and smallpox), vector-borne diseases (e.g., zika), urban disaster preparedness, contagious violence, the evolution of norms, economic dynamics, computational archaeology, and the emergence of social classes, among many other topics. His books include Nonlinear Dynamics, Mathematical Biology, and Social Science (Wiley 1997), Generative Social Science: Studies in Agent-Based Computational Modeling (Princeton, 2006), Agent_Zero: Toward Neurocognitive Foundations for Generative Social Science (Princeton, 2013), and with Robert Axtell, Growing Artificial Societies: Social Science from the Bottom Up (MIT, 1996). Dr. Epstein earned his BA from Amherst College and his Ph.D. from The Massachusetts Institute of Technology. 

</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held virtually on Zoom. Please join via Zoom at the link provided: ([link](`r zoom_url`)).

</p>

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a group comment (one post/group) on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository. </a> We will use a rotation system for group posting. All group 1 sub-groups are expected to post a question and attend this week, but group 2 sub-groups do not need to post and attendance is optional.

This week's readings include excerpts from a single book. The suggested reading is the Preface, first 20 pages of Part 1, and first 20 pages of Part 2. The Preface, Part 1, and Part 2 have been split into separate documents for your convenience:

Preface:
- `r readings0`

Part 1 (first 20 pgs recommended):
- `r readings1`

Part 2 (first 20 pgs recommended):
- `r readings2`

<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:00 a.m. to 12:20 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
