---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "02/10/2022"

quarter <- "Winter2022"

week_folder <- "02-10_Bakkour"


title <- "Sampling from memory to guide decisions"


speaker <- "Akram Bakkour"
department <- "Department of Psychology"
university <- "University of Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2022/issues/5"
zoom_url <- "https://uchicago.zoom.us/j/96755762030?pwd=OHFQb280WU1lWWZib0RGUVZMdG43UT09"


#Papers

week_paper_ref0 <- "Bakkour, A., Palombo, D. J., Zylberberg, A., Kang, Y. H., Reid, A., Verfaellie, M., ... & Shohamy, D. (2019). The hippocampus supports deliberation during value-based decisions. elife, 8, e46080."
week_paper_file0 <- "Bakkour_elife_2019.pdf"

#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Decisions arise through a process of deliberation comprising evaluation of evidence and consideration of the values associated with options. However, the cognitive and neural mechanisms of deliberation during decisions based on preferences, in particular, remain poorly understood. To address this gap, my work leverages a neural and computational framework that posits that evidence is sampled over time, and when enough evidence is sampled, a commitment to a choice is made. This sequential sampling with optional stopping framework links deliberation to reaction time and offers testable hypotheses about the relationship between evidence, choice, and the time it takes to make that choice. For decisions about a perceptual stimulus, most of the evidence derives from information external to the organism. For decisions based on preferences, the evidence must derive from internal processes. The central hypothesis guiding my work is that internal evidence is derived from relational memory mechanisms that rely on the hippocampus. In this talk, I will present a series of studies that draw on behavior, neuroimaging and computational modeling in healthy individuals and patients with known cognitive deficits. The findings lay the foundation for a mechanistic understanding of how sampling from memory may enable the construction of value and guide decision making.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>

<br><br>

<p class=footertext2>

**Akram Bakkour** received a BS in Neuroscience from Brown University and a PhD in Neuroscience from The University of Texas at Austin. He then completed his postdoctoral training at Columbia University before moving to Chicago. Akram is currently an Assistant Professor in the Department of Psychology at The University of Chicago and directs the Memory and Decision Lab. His research focuses on the cognitive neuroscience of memory and decision making. He is interested in exploring the computational, cognitive, and neural mechanisms by which relational memory supports value-based decision making in health and disease.
</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held virtually on Zoom and in-person in room 295 of 1155 East 60th St. If joining virtually, please join via Zoom ([link](`r zoom_url`)).

</p>

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a group comment (one post/group) on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository. </a> We will use a rotation system for group posting. All group 2 sub-groups are expected to post a question and attend this week, but group 1 sub-groups do not need to post and attendance is optional.

This week's readings:

- `r readings0`

Please find the supplemental information online [here](https://elifesciences.org/articles/46080) 

<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:00 a.m. to 12:20 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
